_BASE_: "../COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
MODEL:
  WEIGHTS: "./models/stfar_coco_r50_fpn_student_converted_detectron2_style.pth"
  RESNETS:
    NORM: "BN"
    OUT_FEATURES: [ "stem", "res2", "res3", "res4", "res5" ]
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [1.0, 1.0, 1.0]
INPUT:
  FORMAT: "BGR"
SOLVER:
  IMS_PER_BATCH_TEST: 8
  BASE_LR: 0.0001
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 5.0
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
TEST:
  CONTINUAL_DOMAIN: True
  ANALYSIS: False
  COLLECT_FEATURES: False
  ONLINE_ADAPTATION: False
#  ADAPTATION:
#    SOURCE_FEATS_PATH: "./outputs/COCO/20230726/features_stat.pth"
OUTPUT_DIR: "./outputs/COCO/20231011_direct_test"

