_BASE_: "../COCO-Detection/faster_rcnn_swinT_FPN_1x.yaml"
MODEL:
  WEIGHTS: "models/faster_rcnn_swin-t-p4-w7-fpn_1x_coco_epoch_12_converted_detectron2_style.pth"
  PIXEL_MEAN: [ 103.530, 116.280, 123.675 ]
  PIXEL_STD: [ 1.0, 1.0, 1.0 ]
SOLVER:
  IMS_PER_BATCH_TEST: 4
  BASE_LR: 0.0001
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 5.0
TEST:
  CORRUPT: False
  ANALYSIS: False
OUTPUT_DIR: "./outputs/COCO_TTA/swinT_full_params_update"

