_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./models/swin_tiny_patch4_window7_224_22k_d2.pth"
  MASK_ON: False
  PIXEL_MEAN: [ 103.530, 116.280, 123.675 ]
  # PIXEL_MEAN: [ 123.675, 116.280, 103.530]
  PIXEL_STD: [57.375, 57.120, 58.395]
  # PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  ROI_HEADS:
    NUM_CLASSES: 8
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 370
#  MAX_SIZE_TEST: 1216
DATASETS:
  TRAIN: ('kitti_train', )
  TEST: ('kitti_val', )
SOLVER:
  TYPE: "AdamW"
  IMS_PER_BATCH: 16
  IMS_PER_BATCH_TEST: 1
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.0001
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 5000
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "./outputs/KITTI/faster_rcnn_fpn_swinT_1x"
