_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 8
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 370
DATASETS:
  TRAIN: ('kitti_train', )
  TEST: ('kitti_val',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "./outputs/KITTI/faster_rcnn_fpn_R50_1x"
