_BASE_: "../KITTI/faster_rcnn_R_50_FPN_1x.yaml"
MODEL:
  WEIGHTS: "models/kitti_R50_aug.pth"
SOLVER:
  TYPE: "SGD"
  IMS_PER_BATCH_TEST: 4
  BASE_LR: 0.0001
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 1.0
TEST:
  ONLINE_ADAPTATION: True
  CONTINUAL_DOMAIN: True
  ADAPTATION:
    CONTINUAL: True
    SOURCE_FEATS_PATH: "./models/kitti_R50_aug_feature_stats_new.pt"
    GLOBAL_ALIGN: "KL"
    FOREGROUND_ALIGN: "KL"
    ALPHA_GLOBAL: 1.0
    ALPHA_FOREGROUND: 1.0
    WEIGHT_REG: 0.0
    TH_BG: 0.5
    EMA_GAMMA: 128
    FREQ_WEIGHT: True
  ADAPTER:
    TYPE: "parallel"
OUTPUT_DIR: "./outputs/KITTI/R50_CTA"
