_BASE_: "../PascalVOC-Detection/faster_rcnn_R_50_FPN.yaml"
MODEL:
  WEIGHTS: "./models/detectron2_faster_rcnn_r50_fpn_1x_voc0712_20220320_192712-54bef0f3.pth"
  RESNETS:
    STRIDE_IN_1X1: False
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 700
SOLVER:
  IMS_PER_BATCH_TEST: 8
  BASE_LR: 0.00001
  CLIP_GRADIENTS:
    ENABLED: True
TEST:
  CORRUPT: True
  ANALYSIS: True
  ONLINE_ADAPTATION: False
  ADAPTATION:
    TYPE: None
    SOURCE_FEATS_PATH: "./outputs/VOC/Source_Feats_0704/features_stat.pth"
    SOURCE_FEATS_NUM: 5000
    GLOBAL_ALIGN: "KL"
    FOREGROUND_ALIGN: False
    WEIGHT_REG: 1.0
OUTPUT_DIR: "./outputs/VOC_TTA/tmp"
