_BASE_: "./VOC_Corrupted.yaml"
DATASETS:
  TEST: ('watercolor2k_traintest', )
SOLVER:
  BASE_LR: 0.00001
TEST:
  ROI_HEADS:
    RESET_IDX: [1, 2, 6, 7, 11, 14]
  CORRUPT: False
  ANALYSIS: True
  ONLINE_ADAPTATION: True
  ADAPTATION:
    GLOBAL_ALIGN: "KL"
    FOREGROUND_ALIGN: False
    ENLARGE_BN_LR: False
OUTPUT_DIR: "./outputs/Watercolor_TTA/global_0.1_align_0711_lr1e-5"
